site_name: Barinsta
repo_url: https://github.com/austinhuang0131/barinsta
edit_uri: ''
site_description: The open source Instagram client on Android!
site_author: Austin Huang, https://austinhuang.me
copyright: 'Documentation: Copyright &copy; 2020 <a href="https://austinhuang.me">Austin Huang</a>. Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.'
nav:
    - Home: index.md
    - Frequently-Asked Questions: faq.md
    - A note on Addiction: addictions.md
    - Legal stuff:
        - Terms & Conditions: tos.md
        - Privacy Policy: privacy.md
    - Donations: https://austinhuang.me/donate
theme: readthedocs

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
